// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2eOPdm2_3zA8xOao-6B2mEZWokExw4aY',
    appId: '1:5120326931:web:3919843d58c4a925d46ee6',
    messagingSenderId: '5120326931',
    projectId: 'conversai-5d653',
    authDomain: 'conversai-5d653.firebaseapp.com',
    storageBucket: 'conversai-5d653.firebasestorage.app',
    measurementId: 'G-NBRV8FB8TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVQUA4OBIEuTYVIgGeGHKzlxtTs_g4kYE',
    appId: '1:5120326931:android:c1e5c51b6342dfadd46ee6',
    messagingSenderId: '5120326931',
    projectId: 'conversai-5d653',
    storageBucket: 'conversai-5d653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAroHdhRzkKVYroEG-9A7mu7iq1-lVvMyM',
    appId: '1:5120326931:ios:4bff082411eb8438d46ee6',
    messagingSenderId: '5120326931',
    projectId: 'conversai-5d653',
    storageBucket: 'conversai-5d653.firebasestorage.app',
    iosBundleId: 'com.example.conversai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAroHdhRzkKVYroEG-9A7mu7iq1-lVvMyM',
    appId: '1:5120326931:ios:4bff082411eb8438d46ee6',
    messagingSenderId: '5120326931',
    projectId: 'conversai-5d653',
    storageBucket: 'conversai-5d653.firebasestorage.app',
    iosBundleId: 'com.example.conversai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2eOPdm2_3zA8xOao-6B2mEZWokExw4aY',
    appId: '1:5120326931:web:26e96332a35b7f8ad46ee6',
    messagingSenderId: '5120326931',
    projectId: 'conversai-5d653',
    authDomain: 'conversai-5d653.firebaseapp.com',
    storageBucket: 'conversai-5d653.firebasestorage.app',
    measurementId: 'G-P04EB67J04',
  );
}
